# Generated by Django 4.1.1 on 2022-11-16 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CVEmp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
