# Generated by Django 4.1.1 on 2022-11-16 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CVEmp', '0002_alter_employee_emp_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
