# Generated by Django 4.1.3 on 2022-11-17 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CVEmp', '0003_alter_employee_emp_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ('emp_name', 'emp_code')},
        ),
    ]
