# Generated by Django 4.1.1 on 2022-11-18 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CVEmp', '0006_remove_profile_id_alter_profile_emp'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_img',
            field=models.ImageField(null=True, upload_to='employee/%Y/%m'),
        ),
    ]
